DROP TABLE IF EXISTS FILE_INFO;
CREATE TABLE FILE_INFO (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  FILENAME varchar(255)  DEFAULT NULL,
  IDENTIFIER varchar(255)  DEFAULT NULL,
  LOCATION varchar(255)  DEFAULT NULL,
  TOTAL_SIZE bigint(20) DEFAULT NULL,
  TYPE varchar(255)  DEFAULT NULL,
  PRIMARY KEY (ID)
);