DROP TABLE IF EXISTS PT_PROGRAM_BUSI_TYPE;
CREATE TABLE PT_PROGRAM_BUSI_TYPE (
  DICT_ID varchar(20)  NOT NULL COMMENT '交易码',
  SUB_ID varchar(20)  DEFAULT NULL,
  BUSI_TYPE varchar(4)  NOT NULL COMMENT '业务类型',
  COMM varchar(100)  DEFAULT NULL COMMENT '描述',
  ORDERID int DEFAULT NULL COMMENT '排序',
  ACTIVE varchar(1)  DEFAULT '1',
  PRIMARY KEY (DICT_ID,BUSI_TYPE)
);

alter table PT_PROGRAM_BUSI_TYPE COMMENT '交易与业务类型映射表';