DROP TABLE IF EXISTS `pt_tran_category`;
CREATE TABLE `pt_tran_category`  (
  `FORMAT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '渠道类型',
  `TRAN_CATEGORY` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '业务种类',
  `MSG_CODE` varchar(35) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '报文代码',
  `TRAN_CATEGORY_NAME` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '业务种类名称',
  `BUSI_TYPE` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '业务类型',
  `BUSI_TYPE_NAME` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '业务类型名称',
  `UPDATE_DATE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新日期',
  PRIMARY KEY (`FORMAT`, `MSG_CODE`, `BUSI_TYPE`, `TRAN_CATEGORY`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '业务类型业务种类对应表' ROW_FORMAT = Dynamic;