DROP TABLE IF EXISTS SYS_ROLE;
CREATE TABLE SYS_ROLE (
  ROLE_ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  ROLE_NAME varchar(100)  DEFAULT NULL COMMENT '角色名称',
  ROLE_SIGN varchar(100)  DEFAULT NULL,
  REMARK varchar(100)  DEFAULT NULL COMMENT '角色描述',
  USER_ID_CREATE bigint(20) DEFAULT NULL,
  GMT_CREATE datetime DEFAULT NULL COMMENT '创建时间',
  GMT_MODIFIED datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (ROLE_ID)
);

alter table SYS_ROLE comment '角色管理';