DROP TABLE IF EXISTS SYS_AUTO_PMKEY;
CREATE TABLE SYS_AUTO_PMKEY (
  PK_NAME varchar(50)  NOT NULL COMMENT '主键名称',
  PK_LEN bigint(20) DEFAULT NULL COMMENT '主键长度',
  STEP_LEN bigint(20) DEFAULT NULL COMMENT '步长',
  MAX_VALUE bigint(20) DEFAULT NULL COMMENT '最大值',
  PREFIX varchar(10)  DEFAULT NULL COMMENT '前缀',
  TABLE_NAME varchar(50)  DEFAULT NULL COMMENT '表名称',
  COL_ID varchar(60)  DEFAULT NULL COMMENT '字段',
  SYS_CD varchar(10)  DEFAULT NULL COMMENT '系统编号',
  RESET_DATE varchar(10)  DEFAULT NULL COMMENT '重置日期',
  RESET_FREQ varchar(2)  DEFAULT NULL COMMENT '重置频率',
  REMARK varchar(255)  DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (PK_NAME)
);