DROP TABLE IF EXISTS SYS_USER_EXT_INFO;
CREATE TABLE SYS_USER_EXT_INFO (
  USER_ID bigint(20)  NOT NULL COMMENT '用户号',
  E_NO varchar(125)  DEFAULT NULL COMMENT '员工编号',
  P_NO varchar(125)  DEFAULT NULL COMMENT '人员编号',
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES SYS_USER(ID)
);

alter table SYS_USER_EXT_INFO comment '用户管理扩展表';