DROP TABLE IF EXISTS SYS_DEPT;
CREATE TABLE SYS_DEPT (
  DEPT_ID bigint(20) NOT NULL AUTO_INCREMENT,
  PARENT_ID bigint(20) DEFAULT NULL COMMENT '上级部门ID，一级部门为0',
  DEPT_NAME varchar(50) DEFAULT NULL COMMENT '部门名称',
  ORDER_NUM int(11) DEFAULT NULL COMMENT '排序',
  ORG_ID varchar(10)  DEFAULT NULL COMMENT '机构号',
  DEL_FLAG tinyint DEFAULT '0' COMMENT '是否删除  -1：已删除  0：正常',
  PRIMARY KEY (DEPT_ID)
);

alter table SYS_DEPT comment '部门管理';