DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE (
  USER_ROLE_ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户与角色关系ID',
  USER_ID bigint(20) DEFAULT NULL COMMENT '用户ID',
  ROLE_ID bigint(20) DEFAULT NULL COMMENT '角色ID',
  PRIMARY KEY (USER_ROLE_ID)
);

alter table SYS_USER_ROLE comment '用户与角色对应关系';

