DROP TABLE IF EXISTS SYS_DICT;
CREATE TABLE SYS_DICT (
  DICT_ID bigint(64) NOT NULL AUTO_INCREMENT COMMENT '标签ID',
  DICT_NAME varchar(100) DEFAULT NULL COMMENT '标签名',
  DICT_VALUE varchar(100) DEFAULT NULL COMMENT '数据值',
  DICT_TYPE varchar(100) DEFAULT NULL COMMENT '类型',
  DESCRIPTION varchar(100) DEFAULT NULL COMMENT '描述',
  DICT_SORT bigint(64) DEFAULT NULL COMMENT '排序（升序）',
  PARENT_ID bigint(64) DEFAULT NULL COMMENT '父级编号',
  CREATE_BY bigint(64) DEFAULT NULL COMMENT '创建者',
  CREATE_DATE datetime DEFAULT NULL COMMENT '创建时间',
  UPDATE_BY bigint(64) DEFAULT NULL COMMENT '更新者',
  UPDATE_DATE datetime DEFAULT NULL COMMENT '更新时间',
  REMARKS varchar(255) DEFAULT NULL COMMENT '备注信息',
  DEL_FLAG char(1) DEFAULT NULL COMMENT '删除标记',
  APP_NAME varchar(20) DEFAULT NULL,
  PRIMARY KEY (DICT_ID)
);

alter table SYS_DICT comment '字典表';