DROP TABLE IF EXISTS SYS_ORG;
CREATE TABLE SYS_ORG (
  ORG_ID varchar(20)  NOT NULL COMMENT '机构',
  ORG_NAME varchar(100)  DEFAULT NULL COMMENT '机构名称',
  NAME_EN varchar(255)  DEFAULT NULL COMMENT '名称英文',
  LEVEL_CD varchar(10)  DEFAULT NULL COMMENT '级次',
  UP_ORG_ID varchar(60)  DEFAULT NULL COMMENT '上级机构编号',
  ORDER_NUM int DEFAULT NULL COMMENT '排序',
  STATUS varchar(1)  DEFAULT NULL COMMENT '状态',
  ORG_FLAG varchar(1)  DEFAULT NULL COMMENT '机构标志:0-虚拟机构；1-实体机构',
  COMPANY_FLAG varchar(1)  DEFAULT NULL COMMENT '法人机构标志:0-否；1-是',
  TEL varchar(30)  DEFAULT NULL COMMENT '电话',
  ADDRESS varchar(255)  DEFAULT NULL COMMENT '地址',
  COMPANY varchar(20)  DEFAULT NULL COMMENT '法人',
  CORPERATION varchar(255)  DEFAULT NULL COMMENT '法人信息',
  PRIMARY KEY (ORG_ID)
);

alter table SYS_ORG comment '机构管理';