DROP TABLE IF EXISTS SYS_ROLE_MENU;
CREATE TABLE SYS_ROLE_MENU (
  ROLE_MENU_ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT '角色与菜单关联ID',
  ROLE_ID bigint(20) DEFAULT NULL COMMENT '角色ID',
  MENU_ID bigint(20) DEFAULT NULL COMMENT '菜单ID',
  PRIMARY KEY (ROLE_MENU_ID)
);

alter table SYS_ROLE_MENU comment '角色管理';