DROP TABLE IF EXISTS SYS_LOGIN_LOG;
CREATE TABLE SYS_LOGIN_LOG (
  LOG_ID bigint(20) NOT NULL AUTO_INCREMENT,
  USER_ID bigint(20)  DEFAULT NULL COMMENT '用户编号',
  IP_ADDRESS varchar(15)  DEFAULT NULL COMMENT '执行者ip',
  ADDRESS varchar(255)  DEFAULT NULL COMMENT '地址',
  BROWSER_TYPE varchar(20)  DEFAULT NULL COMMENT '浏览器类型',
  OS_TYPE varchar(20)  DEFAULT NULL COMMENT '操作系统类型',
  LOGIN_STATUS varchar(2)  DEFAULT NULL COMMENT '登录状态: S-成功 F-失败',
  ERR_MSG text  COMMENT '错误消息',
  SYS_TIME varchar(20)  DEFAULT NULL COMMENT '操作时间',
  PRIMARY KEY (LOG_ID)
);